
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://pjsyaeztmnslniklmsvy.supabase.co';
const serviceRoleKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqc3lhZXp0bW5zbG5pa2xtc3Z5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTE5NDI3NCwiZXhwIjoyMDg0NzcwMjc0fQ.rZmD0VrDix9s9WabMMHRlSSjzseEqvl_3y_9HlO0pzQ';

const supabase = createClient(supabaseUrl, serviceRoleKey);

const sql = `
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_en TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  stock INTEGER DEFAULT 0,
  image_url TEXT DEFAULT '/hero-dates.png',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  total_amount DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Delivered', 'Cancelled')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

INSERT INTO products (name_en, name_ar, price, stock)
VALUES 
  ('Premium Majdool Box', 'صندوق مجدول فاخر', 120, 45),
  ('Ajwa Dates Gift Set', 'طقم هدايا تمر عجوة', 200, 20),
  ('Sukkari VIP Packet', 'باكيت سكري VIP', 85, 100)
ON CONFLICT DO NOTHING;

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Using a trick to run arbitrary SQL if rpc is not setup:
-- Since we are using service role, we can just insert into tables normally.
-- To run DDL, we usually need a specific RPC or the management API.
`;

async function setup() {
    // Note: supabase-js doesn't have a direct 'execute sql' method for DDL unless you have a custom RPC.
    // So I will just print the instructions for the user as a fallback.
    console.log("Please run the following SQL in your Supabase SQL Editor:");
    console.log(sql);
}

setup();
