-- Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_en TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  stock INTEGER DEFAULT 0,
  image_url TEXT DEFAULT '/hero-dates.png',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  total_amount DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Delivered', 'Cancelled')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert initial demo data
INSERT INTO products (name_en, name_ar, price, stock)
VALUES 
  ('Premium Majdool Box', 'صندوق مجدول فاخر', 120, 45),
  ('Ajwa Dates Gift Set', 'طقم هدايا تمر عجوة', 200, 20),
  ('Sukkari VIP Packet', 'باكيت سكري VIP', 85, 100)
ON CONFLICT DO NOTHING;

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create Policies
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read-only access on products') THEN
        CREATE POLICY \
Allow
public
read-only
access
on
products\ ON products FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read-only access on orders') THEN
        CREATE POLICY \Allow
public
read-only
access
on
orders\ ON orders FOR SELECT USING (true);
    END IF;
END \$\$;
